name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  # Кастомный домен. Если деплоишь ТОЛЬКО на kaifutsi.github.io/maa-finn — оставь пустым.
  CUSTOM_DOMAIN: www.maafinn.com
  # Больше памяти для сборки Next
  NODE_OPTIONS: --max_old_space_size=4096
  # Бейдж билда (можешь вывести в UI через process.env.*)
  NEXT_PUBLIC_BUILD_SHA: ${{ github.sha }}
  NEXT_PUBLIC_BUILD_TIME: ${{ github.run_started_at }}
  # Включаем красивую заглушку для ИИ-виджета/произношения на статику
  NEXT_PUBLIC_AI_DISABLED: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      # ✂️ Убираем серверные роуты (Next export несовместим с app/api/*)
      - name: Strip server routes for static export
        run: |
          if [ -d "app/api" ]; then
            rm -rf app/api
            echo "Removed app/api for static export"
          fi

      # Next.js с output:'export' положит статик в ./out
      - name: Build static site (Next.js export)
        run: npm run build

      # страховка: директория out обязательно существует
      - name: Ensure out dir exists
        run: mkdir -p out

      # защита от "пустого" деплоя (если export не случился)
      - name: Fail if out is empty
        run: |
          test -f out/index.html || { echo "No out/index.html after build. Ensure output:'export'."; exit 1; }

      # создаём CNAME только если домен задан
      - name: Create CNAME (custom domain)
        if: ${{ env.CUSTOM_DOMAIN != '' }}
        run: echo "${{ env.CUSTOM_DOMAIN }}" > out/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
